name: CI Build Docker Image Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image-namespace: [wataly]
        image-name: [actions]
        image-version: [hello]
    name: A job to say hello
    steps:
    - uses: actions/checkout@v1
    - name: docker build and push to hub.docker.com
      env:
        docker_username: ${{ secrets.DOCKER_HUB_ID }}
        docker_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: |
        sudo docker login --username=${docker_username} --password=${docker_password}
        sudo docker build -t ${{ matrix.image-namespace }}/${{ matrix.image-name }}:${{ matrix.image-version }} .
        sudo docker push ${{ matrix.image-namespace }}/${{ matrix.image-name }}:${{ matrix.image-version }}